### ISSUE TITLE
running kubernetes-overview closes all open buffers before openning overview buffer 

### ISSUE THREAD

**Issue by AlecTroemel** [kubernetes-el/kubernetes-el#89]
is there an option or way to turn this off?

**Comment by jinnovation** [comment]
This is a zombie issue, but...

If you're referring to *windows* (splits in the Emacs frame) instead of *buffers* (specific views into files etc.), and the fact that `M-x kubernetes-overview` takes over the entire frame, then the variable `kubernetes-commands-display-buffer-function` exists specifically to customize this. I personally set this to `display-buffer` specifically because I find the default behavior of monopolizing the entire frame disruptive and unnecessary 👍

**Comment by jinnovation** [comment]
Closing this issue since `kubernetes-commands-display-buffer-function` is an established solution.
